Repository huynhsontung/Screenbox, pull requests merged in 2025-04, with the labels that each got.

#587 fix: Sentry error reporting for unhandled exceptions
  Screenbox.Core/Screenbox.Core.csproj
  Screenbox.Core/packages.lock.json
  Screenbox/App.xaml.cs
  Screenbox/Screenbox.csproj
  Screenbox/packages.lock.json
Labels: bug, size:M

#584 chore: refactor and add comments to thickness converter
  Screenbox/App.xaml
  Screenbox/Converters/ThicknessFilterConverter.cs
Labels: size:L, lgtm

#588 feat: migrate to ReswPlus Source Generator
  Screenbox/Screenbox.csproj
  Screenbox/Strings/en-US/KeyboardResources.generated.cs
  Screenbox/Strings/en-US/Resources.generated.cs
  Screenbox/packages.lock.json
Labels: enhancement, size:XL

#562 style: update system caption button colors
  Screenbox/App.xaml.cs
  Screenbox/Controls/OpenUrlDialog.xaml.cs
  Screenbox/Controls/PropertiesDialog.xaml.cs
  Screenbox/Controls/PropertiesView.xaml
  Screenbox/Controls/SetOptionsDialog.xaml.cs
  Screenbox/Controls/VLCLoginDialog.xaml.cs
  Screenbox/Helpers/TitleBarHelper.cs
  Screenbox/Pages/MainPage.xaml.cs
  Screenbox/Pages/PlayerPage.xaml
  Screenbox/Pages/PlayerPage.xaml.cs
  Screenbox/Screenbox.csproj
Labels: enhancement, size:L

#581 style: add new icons for a few settings
  Screenbox/Assets/Fonts/ScreenboxFluentIcons.ttf
  Screenbox/Assets/Fonts/ScreenboxMDL2Assets.ttf
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Pages/SettingsPage.xaml.cs
  Screenbox/Styles/Icon.xaml
  assets/fonts/ScreenboxFluentIcons.ufo/fontinfo.plist
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/contents.plist
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uF_00B_7.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uF_00B_8.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uF_00B_9.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uF_00B_A_.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uF_00F_0.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uF_00F_1.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uF_010D_.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uF_010E_.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uniE_74D_.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uniE_795.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uniE_A_20.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uniE_A_66.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uniE_E_47.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uniE_E_49.glif
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uniF_353.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/fontinfo.plist
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/contents.plist
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uF_00B_7.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uF_00B_9.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uF_00F_0.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uF_00F_1.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uF_010D_.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uF_010E_.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uniE_795.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uniE_A_20.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uniE_A_66.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uniE_E_71.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uniF_353.glif
Labels: enhancement, size:M

#592 fix: handle total chapters duration different from media duration
  Screenbox/Controls/ChapterProgressBar.xaml.cs
  Screenbox/Screenbox.csproj
Labels: bug, size:M

#578 l10n: Crowdin updates
  Screenbox/Strings/ar-SA/Resources.resw
  Screenbox/Strings/he-IL/Resources.resw
  Screenbox/Strings/it-IT/Resources.resw
  Screenbox/Strings/pl-PL/Resources.resw
  Screenbox/Strings/pt-BR/Resources.resw
  Screenbox/Strings/pt-PT/Resources.resw
  Screenbox/Strings/ro-RO/Resources.resw
  Screenbox/Strings/tr-TR/Resources.resw
  Screenbox/Strings/vi/ManifestResources.resw
  Screenbox/Strings/vi/Resources.resw
  Screenbox/Strings/zh-Hans/Resources.resw
Labels: l10n, crowdin, size:L
