Repository huynhsontung/Screenbox, pull requests merged in 2025-06, with the labels that each got.

#593 feat: add option to hide chapter name
  Screenbox.Core/Services/ISettingsService.cs
  Screenbox.Core/Services/SettingsService.cs
  Screenbox.Core/ViewModels/PlayerControlsViewModel.cs
  Screenbox.Core/ViewModels/SettingsPageViewModel.cs
  Screenbox/Controls/PlayerControls.xaml
  Screenbox/Controls/TimeDisplay.xaml.cs
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Strings/en-US/Resources.resw
Labels: enhancement, size:M

#616 chore: minor improvements to the ThicknessFilterConverter
  Screenbox/App.xaml
  Screenbox/Converters/ThicknessFilterConverter.cs
  Screenbox/Styles/Button.xaml
Labels: size:L

#617 chore: fix warning and minor improvements
  Screenbox.Core/Playback/PlaybackVideoTrackList.cs
  Screenbox/Pages/MainPage.xaml
  Screenbox/Pages/SettingsPage.xaml
Labels: size:S

#619 chore: refactor PlaylistView selection handling
  Screenbox.Core/ViewModels/CommonViewModel.cs
  Screenbox/Controls/PlaylistView.xaml
  Screenbox/Controls/PlaylistView.xaml.cs
Labels: size:M

#623 feat: add option to change the app's display language
  Screenbox.Core/Models/Language.cs
  Screenbox.Core/Screenbox.Core.csproj
  Screenbox.Core/ViewModels/SettingsPageViewModel.cs
  Screenbox/Converters/LanguageLayoutDirectionToFlowDirectionConverter.cs
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Pages/SettingsPage.xaml.cs
  Screenbox/Screenbox.csproj
  Screenbox/Strings/en-US/Resources.resw
Labels: l10n, size:L
