Repository huynhsontung/Screenbox, pull requests merged in 2025-02, with the labels that each got.

#553 feat: enrich Sentry error reporting
  .github/workflows/main.yml
  Screenbox.Core/ViewModels/CastControlViewModel.cs
  Screenbox.Core/ViewModels/MediaListViewModel.cs
  Screenbox/App.xaml.cs
  Screenbox/Pages/MainPage.xaml.cs
Labels: enhancement, size:L

#546 style: minor UI fixes and optimizations
  Screenbox/App.xaml
  Screenbox/Controls/CompositeTrackPicker.xaml
  Screenbox/Controls/NotificationView.xaml.cs
  Screenbox/Controls/PlaylistView.xaml
  Screenbox/Pages/AlbumDetailsPage.xaml
  Screenbox/Pages/ArtistDetailsPage.xaml
  Screenbox/Pages/HomePage.xaml.cs
  Screenbox/Pages/MainPage.xaml
  Screenbox/Pages/MainPage.xaml.cs
  Screenbox/Pages/PlayerPage.xaml
  Screenbox/Pages/PlayerPage.xaml.cs
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Pages/SettingsPage.xaml.cs
  Screenbox/Styles/Button.xaml
  Screenbox/Styles/ItemContainer.xaml
Labels: size:M, lgtm

#542 feat: add customizable application theme
  Screenbox.Core/Enums/SettingsOptions.cs
  Screenbox.Core/Services/ISettingsService.cs
  Screenbox.Core/Services/SettingsService.cs
  Screenbox.Core/ViewModels/SettingsPageViewModel.cs
  Screenbox/App.xaml.cs
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Strings/en-US/Resources.generated.cs
  Screenbox/Strings/en-US/Resources.resw
Labels: size:L, lgtm

#545 refactor: unify video and music cache
  Screenbox.Core/Models/IMediaProperties.cs
  Screenbox.Core/Models/MediaInfo.cs
  Screenbox.Core/Models/MusicInfo.cs
  Screenbox.Core/Models/PersistentMediaRecord.cs
  Screenbox.Core/Models/PersistentStorageLibrary.cs
  Screenbox.Core/Models/PersistentVideoLibrary.cs
  Screenbox.Core/Models/PersistentVideoRecord.cs
  Screenbox.Core/Models/VideoInfo.cs
  Screenbox.Core/Screenbox.Core.csproj
  Screenbox.Core/Services/LibraryService.cs
Labels: bug, enhancement, size:L

#558 fix: unexpected lively player load due to Storyboard animation
  Screenbox/Pages/PlayerPage.xaml
Labels: bug, size:XS

#560 chore: update and format editor config file
  .editorconfig
  NOTICE.md
Labels: size:L

#559 style: add theme mode setting glyph
  Screenbox.Core/Properties/AssemblyInfo.cs
  Screenbox/Assets/Fonts/ScreenboxFluentIcons.ttf
  Screenbox/Assets/Fonts/ScreenboxMDL2Assets.ttf
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Properties/AssemblyInfo.cs
  Screenbox/Styles/Icon.xaml
  assets/fonts/ScreenboxFluentIcons.ufo/fontinfo.plist
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/contents.plist
  assets/fonts/ScreenboxFluentIcons.ufo/glyphs/uniE_795.glif
  assets/fonts/ScreenboxMDL2Assets.ufo/fontinfo.plist
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/contents.plist
  assets/fonts/ScreenboxMDL2Assets.ufo/glyphs/uniE_795.glif
Labels: enhancement, size:S

#550 style: improve split button design and interaction
  Screenbox/App.xaml
  Screenbox/Controls/Extensions/SplitButtonExtensions.cs
  Screenbox/Controls/Interactions/SplitButtonAccessibilityBehavior.cs
  Screenbox/Controls/Interactions/SplitButtonXYNavigationBehavior.cs
  Screenbox/Converters/ThicknessFilterConverter.cs
  Screenbox/Pages/HomePage.xaml
  Screenbox/Pages/PlayQueuePage.xaml
  Screenbox/Screenbox.csproj
  Screenbox/Styles/Button.xaml
Labels: lgtm

#561 feat: improve app theme change
  Screenbox.Core/Helpers/EnumExtensions.cs
  Screenbox.Core/Screenbox.Core.csproj
  Screenbox.Core/ViewModels/CommonViewModel.cs
  Screenbox.Core/ViewModels/PlayerPageViewModel.cs
  Screenbox.Core/ViewModels/SettingsPageViewModel.cs
  Screenbox/App.xaml.cs
  Screenbox/Pages/PlayerPage.xaml
  Screenbox/Pages/PlayerPage.xaml.cs
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Strings/en-US/Resources.generated.cs
  Screenbox/Strings/en-US/Resources.resw
Labels: enhancement, size:L

#563 chore: minor editorconfig update
  .editorconfig
Labels: size:S, lgtm

#556 feat: improve and add new shortcuts
  Screenbox.Core/ViewModels/MainPageViewModel.cs
  Screenbox/Controls/PlayerControls.xaml
  Screenbox/Controls/PlaylistView.xaml
  Screenbox/Pages/MainPage.xaml
  Screenbox/Pages/MainPage.xaml.cs
  Screenbox/Screenbox.csproj
Labels: lgtm

#568 chore: minor improvement to thickness converter
  Screenbox/App.xaml
  Screenbox/Controls/MediaListViewItem.xaml
  Screenbox/Controls/PlayerControls.xaml
  Screenbox/Converters/ThicknessFilterConverter.cs
  Screenbox/Styles/Button.xaml
Labels: enhancement, size:L, lgtm

#544 style: critical error panel redesign
  Screenbox/Pages/MainPage.xaml
  Screenbox/Strings/en-US/Resources.generated.cs
  Screenbox/Strings/en-US/Resources.resw
Labels: size:L, lgtm

#530 feat: add option to always resume from the last position
  Screenbox.Core/Common/ServiceHelpers.cs
  Screenbox.Core/Helpers/LastPositionTracker.cs
  Screenbox.Core/Services/ISettingsService.cs
  Screenbox.Core/Services/SettingsService.cs
  Screenbox.Core/ViewModels/PlayerPageViewModel.cs
  Screenbox.Core/ViewModels/SeekBarViewModel.cs
  Screenbox.Core/ViewModels/SettingsPageViewModel.cs
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Strings/en-US/Resources.generated.cs
  Screenbox/Strings/en-US/Resources.resw
Labels: enhancement, size:L

#575 style: minor UI improvements
  Screenbox/Pages/SettingsPage.xaml
  Screenbox/Styles/CommandBar.xaml
Labels: a11y, size:S, lgtm

#576 feat: drag and drop anywhere to play
  Screenbox.Core/Messages/DragDropMessage.cs
  Screenbox.Core/Screenbox.Core.csproj
  Screenbox.Core/ViewModels/HomePageViewModel.cs
  Screenbox.Core/ViewModels/MainPageViewModel.cs
  Screenbox.Core/ViewModels/PlayerPageViewModel.cs
  Screenbox.Core/ViewModels/PlaylistViewModel.cs
  Screenbox/Controls/PlaylistView.xaml.cs
  Screenbox/Pages/HomePage.xaml
  Screenbox/Pages/HomePage.xaml.cs
  Screenbox/Pages/MainPage.xaml
  Screenbox/Pages/MainPage.xaml.cs
  Screenbox/Pages/PlayerPage.xaml
  Screenbox/Pages/PlayerPage.xaml.cs
Labels: enhancement, size:L

#536 l10n: Crowdin updates
  Screenbox/Strings/ar-SA/Resources.resw
  Screenbox/Strings/be-BY/Resources.resw
  Screenbox/Strings/de-DE/Resources.resw
  Screenbox/Strings/el-GR/Resources.resw
  Screenbox/Strings/es-ES/ManifestResources.resw
  Screenbox/Strings/es-ES/Resources.resw
  Screenbox/Strings/fa-IR/Resources.resw
  Screenbox/Strings/fr-FR/KeyboardResources.resw
  Screenbox/Strings/fr-FR/ManifestResources.resw
  Screenbox/Strings/fr-FR/Resources.resw
  Screenbox/Strings/he-IL/Resources.resw
  Screenbox/Strings/hu-HU/Resources.resw
  Screenbox/Strings/id-ID/Resources.resw
  Screenbox/Strings/it-IT/ManifestResources.resw
  Screenbox/Strings/it-IT/Resources.resw
  Screenbox/Strings/ja-JP/Resources.resw
  Screenbox/Strings/ko-KR/Resources.resw
  Screenbox/Strings/ms-MY/Resources.resw
  Screenbox/Strings/nl-NL/Resources.resw
  Screenbox/Strings/pl-PL/Resources.resw
  Screenbox/Strings/pt-BR/Resources.resw
  Screenbox/Strings/pt-PT/Resources.resw
  Screenbox/Strings/ro-RO/Resources.resw
  Screenbox/Strings/ru-RU/ManifestResources.resw
  Screenbox/Strings/ru-RU/Resources.resw
  Screenbox/Strings/si-LK/Resources.resw
  Screenbox/Strings/sr-SP/Resources.resw
  Screenbox/Strings/sv-SE/Resources.resw
  Screenbox/Strings/ta-IN/Resources.resw
  Screenbox/Strings/tr-TR/Resources.resw
  Screenbox/Strings/uk-UA/ManifestResources.resw
  Screenbox/Strings/uk-UA/Resources.resw
  Screenbox/Strings/vi/ManifestResources.resw
  Screenbox/Strings/vi/Resources.resw
  Screenbox/Strings/zh-Hans/Resources.resw
  Screenbox/Strings/zh-Hant/Resources.resw
Labels: l10n, crowdin, size:XXL
